version: '3'
services:
  mongo:
    image: mongo:3.4.8
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data

  server:
    image: node:8
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    links:
      - mongo:mongo
    volumes:
      - ./api:/home/node/app
    ports:
      - "81:3000"
    command: ["npm", "run", "start"]